# Usa una imagen oficial de PHP con Apache
FROM php:8.2-apache

# Copia el contenido de tu proyecto al contenedor
COPY . /var/www/html/

# Da permisos correctos
RUN chown -R www-data:www-data /var/www/html

# Exponer el puerto 80
EXPOSE 80
